version: '3'
services:
  java:
    image: openjdk:11-slim
    ports:
      - 8080:8080
    volumes:
      - ./server:/server
    working_dir: /server
    depends_on:
      - elasticsearch
    command: ./gradlew bootRun
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0 
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"

